---
title: "Error term lineartiy on balancedness"
author: "Yicheng Shen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r}
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(HLMdiag)
library(nlme)
library(qqplotr)
library(PearsonDS)
library(MASS)
library(gridExtra)
library(doParallel)
library(foreach)
options(warn=-1)
.lmerMod_matrices<- HLMdiag:::.lmerMod_matrices
```
 
 
# Analysis of Model Residuals from same-sized/balanced/unbalanced datasets with/without Linearity violation

Same Group Size:rep(25,50) 
Balanced Group Size: sample(20:30, 50, replace = TRUE) 
Unbalanced Group Size: sample(2:50, 50, replace = TRUE) 


# Generate two-level datasets 

```{r}
set.seed(202167)
sa_simdata.df<- generate_data(50,0,0.5)
ba_simdata.df<- generate_data(50,1,0.5)
ub_simdata.df<- generate_data(50,2,0.5)
```


# Simulation function 

```{r simulation-function-linearity}
sim.hlmlin <- function(simdata.df, rel.dsn) {

sim_design <- simdata.df # Contain id, grouping and two predictors 

b0 <- 5     # Intercept
b1 <- 1       # X_ij slope 
b2 <- 1       # Z_ij slope 
sd_error <- 1  # # std of the error term, default set as e ~ N(0,1)
sd_int   <- 0.5  # random effect of intercept 
sd_slope <- 0.5  # re of slope

re_df <- data.frame(group = 1:50, 
                    intercept = rnorm(50, mean = 0, sd = sd_int),
                    slope = rnorm(50, mean = 0, sd = sd_slope)) # set up REs for intercept and slope 


    if(rel.dsn == "linear") {   # no change
        sim_df <- left_join(sim_design, re_df, by = "group") %>%
  mutate(error = rnorm(nrow(.), mean = 0, sd = sd_error),
         Y_ij = b0 + b1 * X_ij + b2 * Z_ij + intercept + slope * X_ij + error)
    } 

    if(rel.dsn == "sq") {  # squaring Z_ij
        sim_df <- left_join(sim_design, re_df, by = "group") %>%
  mutate(error = rnorm(nrow(.), mean = 0, sd = sd_error),
         Y_ij = b0 + b1 * X_ij + b2 * (Z_ij)^2 + intercept + slope * X_ij + error)
    } 
    
   # y.df <- as.data.frame( as.matrix(sim_df$Y_ij) )
   # colnames(y.df) <- paste("sim_", 1:ncol(y.df), sep = "")
    return( sim_df )
}
```


# Error Term Linearity Simulation

```{r}
rel.dsn <- c("linear","sq") # Linearity Assumption

set.seed(202167)
nsim <- 20  # default as 20; change as needed
model_resid <- vector("list", length = nsim)
sim_model <- vector("list", length = nsim)
first_resid <- vector("list", length = nsim)
sec_resid <- vector("list", length = nsim)

# same size sim
for(k in seq_along(rel.dsn)){
  
same_size_sim.fm <- replicate (nsim, sim.hlmlin(sa_simdata.df,  rel.dsn = rel.dsn[k]))

for(i in seq_along(1:nsim)) {
  sim_model[[i]] <- lmer(Y_ij ~ X_ij + Z_ij + (X_ij | group), data = (same_size_sim.fm)[,i], 
             control = lmerControl(calc.derivs = FALSE))
  
  # level 1 resid
  first_resid[[i]] <- hlm_resid(sim_model[[i]],standardize = T, include.ls = TRUE)
  # level 2 resid
  sec_resid[[i]]<-hlm_resid(sim_model[[i]], level = "group", standardize = T, include.ls = TRUE)
  sec_resid[[i]]$mahalanobis<-mahalanobis_ranef.lmerMod(sim_model[[i]]) 
  # combine into one object
  model_resid[[i]] <-list(first_resid[[i]], sec_resid[[i]])
  names(model_resid[[i]]) = c("first_resid", "second_resid")
}

 saveRDS(model_resid, paste("simulated_models/Result/Linearity/", rel.dsn[k], "_same_size_residuals.RDS", sep = ""))
}


# balanced sim
for(k in seq_along(rel.dsn)){

balanced_sim.fm <-  replicate (nsim, sim.hlmlin(ba_simdata.df,  rel.dsn = rel.dsn[k]))

for(i in seq_along(1:nsim)) {
  sim_model[[i]] <- lmer(Y_ij ~ X_ij + Z_ij + (X_ij | group), data = balanced_sim.fm[,i], 
             control = lmerControl(calc.derivs = FALSE))

  first_resid[[i]] <- hlm_resid(sim_model[[i]],standardize = T, include.ls = TRUE)
  
  sec_resid[[i]]<-hlm_resid(sim_model[[i]], level = "group", standardize = T, include.ls = TRUE)
  sec_resid[[i]]$mahalanobis<-mahalanobis_ranef.lmerMod(sim_model[[i]]) 
  
  model_resid[[i]] <-list(first_resid[[i]], sec_resid[[i]])
  names(model_resid[[i]]) = c ("first_resid", "second_resid")
}

 saveRDS(model_resid, paste("simulated_models/Result/Linearity/", rel.dsn[k], "_balanced_residuals.RDS", sep = ""))
}


# unbalanced sim
for(k in seq_along(rel.dsn)){
  
unbalanced_sim.fm <-replicate (nsim, sim.hlmlin(ub_simdata.df,  rel.dsn = rel.dsn[k]))

for(i in seq_along(1:nsim)) {
  sim_model[[i]] <- lmer(Y_ij ~ X_ij + Z_ij + (X_ij | group), data = unbalanced_sim.fm[,i], 
             control = lmerControl(calc.derivs = FALSE))
  
  first_resid[[i]] <- hlm_resid(sim_model[[i]],standardize = T, include.ls = TRUE)
  
  sec_resid[[i]]<-hlm_resid(sim_model[[i]], level = "group", standardize = T, include.ls = TRUE)
  sec_resid[[i]]$mahalanobis<-mahalanobis_ranef.lmerMod(sim_model[[i]]) 
  
  model_resid[[i]] <-list(first_resid[[i]], sec_resid[[i]])
  names(model_resid[[i]]) = c ("first_resid", "second_resid")
}

 saveRDS(model_resid, paste("simulated_models/Result/Linearity/", rel.dsn[k], "_unbalanced_residuals.RDS", sep = ""))
}

```


# Analysis 

```{r load-data}
# Only use square of fix effect as a violation 
`linear_same_resid` <- readRDS("simulated_models/Result/Linearity/linear_same_size_residuals.RDS")
`sq_same_resid` <- readRDS("simulated_models/Result/Linearity/sq_same_size_residuals.RDS")
`linear_balanced_resid` <- readRDS("simulated_models/Result/Linearity/linear_balanced_residuals.RDS")
`sq_balanced_resid` <- readRDS("simulated_models/Result/Linearity/sq_balanced_residuals.RDS")
`linear_unbalanced_resid` <- readRDS("simulated_models/Result/Linearity/linear_unbalanced_residuals.RDS")
`sq_unbalanced_resid` <- readRDS("simulated_models/Result/Linearity/sq_unbalanced_residuals.RDS")
```


```{r, warning = F}
# Same Sized Grouping anova test
registerDoParallel(cores=2)

linear_model_chol.mar.resid<- foreach(i = 1:nsim) %dopar% {linear_same_resid[[i]]$first_resid$.chol.mar.resid}
sq_model_chol.mar.resid<- foreach(i = 1:nsim) %dopar% {sq_same_resid[[i]]$first_resid$.chol.mar.resid}

linear_model_fittted <- foreach(i = 1:nsim) %dopar% {linear_same_resid[[i]]$first_resid$.mar.fitted}
sq_model_fittted <-  foreach(i = 1:nsim) %dopar% {sq_same_resid[[i]]$first_resid$.mar.fitted}


linear_model_anova_p <- foreach(i = 1:nsim) %dopar% {anova(lm(linear_model_chol.mar.resid[[i]] ~ linear_model_fittted[[i]]),lm(linear_model_chol.mar.resid[[i]] ~ linear_model_fittted[[i]] + I(linear_model_fittted[[i]]^2)))$`Pr(>F)`[2]}

sq_model_anova_p <- foreach(i = 1:nsim) %dopar% {anova(lm(sq_model_chol.mar.resid[[i]] ~ sq_model_fittted[[i]]),lm(sq_model_chol.mar.resid[[i]] ~ sq_model_fittted[[i]] + I(sq_model_fittted[[i]]^2)))$`Pr(>F)`[2]}

length(linear_model_anova_p[c(which(linear_model_anova_p < 0.05))])/nsim
length(sq_model_anova_p[c(which(sq_model_anova_p < 0.05))])/nsim
```


```{r, warning = F}
# Balanced Grouping anova test

registerDoParallel(cores=2)


linear_model_chol.mar.resid<- foreach(i = 1:nsim) %dopar% {linear_balanced_resid[[i]]$first_resid$.chol.mar.resid}
sq_model_chol.mar.resid<- foreach(i = 1:nsim) %dopar% {sq_balanced_resid[[i]]$first_resid$.chol.mar.resid}

linear_model_fittted <- foreach(i = 1:nsim) %dopar% {linear_balanced_resid[[i]]$first_resid$.mar.fitted}
sq_model_fittted <-  foreach(i = 1:nsim) %dopar% {sq_balanced_resid[[i]]$first_resid$.mar.fitted}


linear_model_anova_p <- foreach(i = 1:nsim) %dopar% {anova(lm(linear_model_chol.mar.resid[[i]] ~ linear_model_fittted[[i]]),lm(linear_model_chol.mar.resid[[i]] ~ linear_model_fittted[[i]] + I(linear_model_fittted[[i]]^2)))$`Pr(>F)`[2]}

sq_model_anova_p <- foreach(i = 1:nsim) %dopar% {anova(lm(sq_model_chol.mar.resid[[i]] ~ sq_model_fittted[[i]]),lm(sq_model_chol.mar.resid[[i]] ~ sq_model_fittted[[i]] + I(sq_model_fittted[[i]]^2)))$`Pr(>F)`[2]}

length(linear_model_anova_p[c(which(linear_model_anova_p < 0.05))])/nsim
length(sq_model_anova_p[c(which(sq_model_anova_p < 0.05))])/nsim
```


```{r, warning = F}
# Unbalanced Grouping anova test
registerDoParallel(cores=2)

linear_model_chol.mar.resid<- foreach(i = 1:nsim)%dopar% {linear_unbalanced_resid[[i]]$first_resid$.chol.mar.resid}
sq_model_chol.mar.resid<- foreach(i = 1:nsim) %dopar% {sq_unbalanced_resid[[i]]$first_resid$.chol.mar.resid}

linear_model_fittted <-foreach(i = 1:nsim) %dopar% {linear_unbalanced_resid[[i]]$first_resid$.mar.fitted}
sq_model_fittted <- foreach(i = 1:nsim) %dopar% {sq_unbalanced_resid[[i]]$first_resid$.mar.fitted}


linear_model_anova_p <- foreach(i = 1:nsim) %dopar% {anova(lm(linear_model_chol.mar.resid[[i]] ~ linear_model_fittted[[i]]),lm(linear_model_chol.mar.resid[[i]] ~ linear_model_fittted[[i]] + I(linear_model_fittted[[i]]^2)))$`Pr(>F)`[2]}

sq_model_anova_p <- foreach(i = 1:nsim) %dopar% {anova(lm(sq_model_chol.mar.resid[[i]] ~ sq_model_fittted[[i]]),lm(sq_model_chol.mar.resid[[i]] ~ sq_model_fittted[[i]] + I(sq_model_fittted[[i]]^2)))$`Pr(>F)`[2]}

length(linear_model_anova_p[c(which(linear_model_anova_p < 0.05))])/nsim
length(sq_model_anova_p[c(which(sq_model_anova_p < 0.05))])/nsim
```



```{r, eval = F}
# Plotting marginal resid. 
k <- sample(1:20, 20, replace = F)
res <- list()
plist <- list()
for(i in 1:length(k)) {
res[[i]] <- hlm_resid(`same_sq_term_models`[[(k[[i]])]],standardize = TRUE)
plist[[i]] <- ggplot(res[[i]], aes(x = .mar.fitted, y = .chol.mar.resid)) + 
    geom_jitter(alpha = 0.3,size = 0.5) +
   labs(y = "mar.resid")+ geom_hline(yintercept = 0, color = "black") +
    theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank())}

n <- length(plist)

nCol <- floor(sqrt(n))

do.call("grid.arrange", c(plist, ncol=nCol))


k <- sample(1:20, 20, replace = F)
res <- list()
plist <- list()
for(i in 1:length(k)) {
res[[i]] <- hlm_resid(`balanced_sq_term_models`[[(k[[i]])]],standardize = TRUE)
plist[[i]] <- ggplot(res[[i]], aes(x = .mar.fitted, y = .chol.mar.resid)) + 
    geom_jitter(alpha = 0.3,size = 0.5) +
   labs(y = "mar.resid")+ geom_hline(yintercept = 0, color = "black") +
    theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank())}

n <- length(plist)

nCol <- floor(sqrt(n))

do.call("grid.arrange", c(plist, ncol=nCol))


k <- sample(1:20, 20, replace = F)
res <- list()
plist <- list()
for(i in 1:length(k)) {
res[[i]] <- hlm_resid(`unbalanced_sq_term_models`[[(k[[i]])]],standardize = TRUE)
plist[[i]] <- ggplot(res[[i]], aes(x = .mar.fitted, y = .chol.mar.resid)) + 
    geom_jitter(alpha = 0.3,size = 0.5) +
   labs(y = "mar.resid")+ geom_hline(yintercept = 0, color = "black") +
    theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank())}

n <- length(plist)

nCol <- floor(sqrt(n))

do.call("grid.arrange", c(plist, ncol=nCol))
```


